import type { RawEvent } from "./events-types";

export const fallbackEvents: RawEvent[] = [
  {
    id: "fallback-1",
    title: "Anna Maria Island Farmers Market",
    summary: "Weekly farmers market featuring local produce, crafts, and live music.",
    description: "Join us every Saturday morning for fresh local produce, handmade crafts, and live entertainment at the Anna Maria Island Farmers Market.",
    startDate: "2026-02-07T08:00:00",
    endDate: "2026-02-07T12:00:00",
    timezone: "America/New_York",
    locationName: "Bridge Street",
    address: "Bridge Street, Bradenton Beach, FL",
    city: "Bradenton Beach",
    state: "FL",
    url: "https://www.annamariaislandchamber.org/events/",
    categories: ["market"],
    tags: ["weekly", "local"],
    source: "AMI Chamber",
  },
  {
    id: "fallback-2",
    title: "Sunset Concert Series",
    summary: "Live acoustic music performances at sunset on the beach.",
    description: "Enjoy live acoustic performances by local musicians as the sun sets over the Gulf of Mexico. Bring your beach chair and relax.",
    startDate: "2026-02-14T18:00:00",
    endDate: "2026-02-14T20:00:00",
    timezone: "America/New_York",
    locationName: "Coquina Beach",
    address: "Coquina Beach, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["music"],
    tags: ["live music", "outdoor"],
    source: "Bradenton Gulf Islands",
  },
  // Holiday Events
  {
    id: "holiday-1",
    title: "Bridge Street Christmas Tree Lighting",
    summary: "Annual Christmas tree lighting ceremony with holiday festivities.",
    description: "Join the community for the annual Christmas tree lighting on Bridge Street. Enjoy holiday music, refreshments, and the magical moment when the tree lights up for the season.",
    startDate: "2026-12-01T18:00:00",
    endDate: "2026-12-01T20:00:00",
    timezone: "America/New_York",
    locationName: "Bridge Street",
    address: "Bridge Street, Bradenton Beach, FL",
    city: "Bradenton Beach",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["holiday"],
    tags: ["christmas", "tree lighting", "free", "family"],
    source: "Fallback",
  },
  {
    id: "holiday-2",
    title: "Anna Maria Island New Year's Eve Beach Celebration",
    summary: "Beachside New Year's Eve celebration with fireworks and live music.",
    description: "Ring in the New Year Anna Maria Island style with a beachside celebration featuring live music, food vendors, and a spectacular fireworks display over the Gulf of Mexico.",
    startDate: "2026-12-31T20:00:00",
    endDate: "2027-01-01T00:30:00",
    timezone: "America/New_York",
    locationName: "Coquina Beach",
    address: "Coquina Beach, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["holiday"],
    tags: ["new years", "fireworks", "beach", "celebration"],
    source: "Fallback",
  },
  {
    id: "holiday-3",
    title: "Fourth of July Fireworks on the Beach",
    summary: "Independence Day fireworks display over the Gulf of Mexico.",
    description: "Celebrate America's birthday with a spectacular fireworks display over the Gulf. Bring your beach chairs, blankets, and enjoy the show with family and friends.",
    startDate: "2026-07-04T19:00:00",
    endDate: "2026-07-04T21:00:00",
    timezone: "America/New_York",
    locationName: "Manatee Public Beach",
    address: "4000 State Road 64, Bradenton Beach, FL",
    city: "Bradenton Beach",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["holiday"],
    tags: ["independence day", "fireworks", "beach", "free"],
    source: "Fallback",
  },
  {
    id: "holiday-4",
    title: "Thanksgiving Beach Walk",
    summary: "Family-friendly beach walk and gratitude ceremony on Thanksgiving morning.",
    description: "Start Thanksgiving with a peaceful beach walk and gratitude ceremony. Perfect for families looking to connect with nature and reflect on the holiday's meaning.",
    startDate: "2026-11-26T09:00:00",
    endDate: "2026-11-26T10:30:00",
    timezone: "America/New_York",
    locationName: "Coquina Beach",
    address: "Coquina Beach, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["holiday"],
    tags: ["thanksgiving", "beach walk", "family", "free"],
    source: "Fallback",
  },
  // Arts & Culture Events
  {
    id: "arts-1",
    title: "Anna Maria Island Art Walk",
    summary: "Monthly gallery walk featuring local artists and live demonstrations.",
    description: "Explore the island's vibrant art scene with this monthly gallery walk. Visit local art galleries, meet artists, watch live demonstrations, and discover unique pieces for your collection.",
    startDate: "2026-02-20T17:00:00",
    endDate: "2026-02-20T21:00:00",
    timezone: "America/New_York",
    locationName: "Bridge Street and Pine Avenue",
    address: "Bridge Street, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["art", "gallery"],
    tags: ["art walk", "gallery", "local artists", "free"],
    source: "Fallback",
  },
  {
    id: "arts-2",
    title: "Bradenton Blues Festival",
    summary: "Annual blues music festival featuring national and regional artists.",
    description: "Experience the soulful sounds of the Bradenton Blues Festival, featuring top blues musicians from around the country. Food vendors, craft beer, and an electric atmosphere.",
    startDate: "2026-03-15T12:00:00",
    endDate: "2026-03-15T22:00:00",
    timezone: "America/New_York",
    locationName: "Lakewood Ranch",
    address: "8330 Lakewood Ranch Blvd, Bradenton, FL",
    city: "Bradenton",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["music", "festival"],
    tags: ["blues", "music festival", "outdoor", "ticketed"],
    source: "Fallback",
  },
  {
    id: "arts-3",
    title: "Village of the Arts First Friday Gallery Walk",
    summary: "Monthly evening gallery walk in Bradenton's historic arts district.",
    description: "Join artists and art lovers for the First Friday Gallery Walk in the Village of the Arts. Explore working artist studios, galleries, and enjoy live music and refreshments.",
    startDate: "2026-02-06T18:00:00",
    endDate: "2026-02-06T21:00:00",
    timezone: "America/New_York",
    locationName: "Village of the Arts",
    address: "1112 12th St W, Bradenton, FL",
    city: "Bradenton",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["art", "gallery"],
    tags: ["gallery walk", "first friday", "art district", "free"],
    source: "Fallback",
  },
  {
    id: "arts-4",
    title: "Anna Maria Island Historical Society Museum Exhibition",
    summary: "Historical exhibition showcasing island heritage and maritime history.",
    description: "Discover the rich history of Anna Maria Island through this special exhibition at the Historical Society Museum. Features artifacts, photographs, and stories from the island's past.",
    startDate: "2026-02-10T10:00:00",
    endDate: "2026-02-10T16:00:00",
    timezone: "America/New_York",
    locationName: "Anna Maria Island Historical Society",
    address: "402 Pine Ave, Anna Maria, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["art", "history"],
    tags: ["museum", "history", "exhibition", "educational"],
    source: "Fallback",
  },
];
