import type { RawEvent } from "./events-types";

export const fallbackEvents: RawEvent[] = [
  {
    id: "fallback-1",
    title: "Anna Maria Island Farmers Market",
    summary: "Weekly farmers market featuring local produce, crafts, and live music.",
    description: "Join us every Saturday morning for fresh local produce, handmade crafts, and live entertainment at the Anna Maria Island Farmers Market.",
    startDate: "2026-02-07T08:00:00",
    endDate: "2026-02-07T12:00:00",
    timezone: "America/New_York",
    locationName: "Bridge Street",
    address: "Bridge Street, Bradenton Beach, FL",
    city: "Bradenton Beach",
    state: "FL",
    url: "https://www.annamariaislandchamber.org/events/",
    categories: ["market"],
    tags: ["weekly", "local"],
    source: "AMI Chamber",
  },
  {
    id: "fallback-2",
    title: "Sunset Concert Series",
    summary: "Live acoustic music performances at sunset on the beach.",
    description: "Enjoy live acoustic performances by local musicians as the sun sets over the Gulf of Mexico. Bring your beach chair and relax.",
    startDate: "2026-02-14T18:00:00",
    endDate: "2026-02-14T20:00:00",
    timezone: "America/New_York",
    locationName: "Coquina Beach",
    address: "Coquina Beach, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["music"],
    tags: ["live music", "outdoor"],
    source: "Bradenton Gulf Islands",
  },
  // Holiday Events
  {
    id: "holiday-1",
    title: "Bridge Street Christmas Tree Lighting",
    summary: "Annual Christmas tree lighting ceremony with holiday festivities.",
    description: "Join the community for the annual Christmas tree lighting on Bridge Street. Enjoy holiday music, refreshments, and the magical moment when the tree lights up for the season.",
    startDate: "2026-12-01T18:00:00",
    endDate: "2026-12-01T20:00:00",
    timezone: "America/New_York",
    locationName: "Bridge Street",
    address: "Bridge Street, Bradenton Beach, FL",
    city: "Bradenton Beach",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["holiday"],
    tags: ["christmas", "tree lighting", "free", "family"],
    source: "Fallback",
  },
  {
    id: "holiday-2",
    title: "Anna Maria Island New Year's Eve Beach Celebration",
    summary: "Beachside New Year's Eve celebration with fireworks and live music.",
    description: "Ring in the New Year Anna Maria Island style with a beachside celebration featuring live music, food vendors, and a spectacular fireworks display over the Gulf of Mexico.",
    startDate: "2026-12-31T20:00:00",
    endDate: "2027-01-01T00:30:00",
    timezone: "America/New_York",
    locationName: "Coquina Beach",
    address: "Coquina Beach, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["holiday"],
    tags: ["new years", "fireworks", "beach", "celebration"],
    source: "Fallback",
  },
  {
    id: "holiday-3",
    title: "Fourth of July Fireworks on the Beach",
    summary: "Independence Day fireworks display over the Gulf of Mexico.",
    description: "Celebrate America's birthday with a spectacular fireworks display over the Gulf. Bring your beach chairs, blankets, and enjoy the show with family and friends.",
    startDate: "2026-07-04T19:00:00",
    endDate: "2026-07-04T21:00:00",
    timezone: "America/New_York",
    locationName: "Manatee Public Beach",
    address: "4000 State Road 64, Bradenton Beach, FL",
    city: "Bradenton Beach",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["holiday"],
    tags: ["independence day", "fireworks", "beach", "free"],
    source: "Fallback",
  },
  {
    id: "holiday-4",
    title: "Thanksgiving Beach Walk",
    summary: "Family-friendly beach walk and gratitude ceremony on Thanksgiving morning.",
    description: "Start Thanksgiving with a peaceful beach walk and gratitude ceremony. Perfect for families looking to connect with nature and reflect on the holiday's meaning.",
    startDate: "2026-11-26T09:00:00",
    endDate: "2026-11-26T10:30:00",
    timezone: "America/New_York",
    locationName: "Coquina Beach",
    address: "Coquina Beach, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["holiday"],
    tags: ["thanksgiving", "beach walk", "family", "free"],
    source: "Fallback",
  },
  // Arts & Culture Events
  {
    id: "arts-1",
    title: "Anna Maria Island Art Walk",
    summary: "Monthly gallery walk featuring local artists and live demonstrations.",
    description: "Explore the island's vibrant art scene with this monthly gallery walk. Visit local art galleries, meet artists, watch live demonstrations, and discover unique pieces for your collection.",
    startDate: "2026-02-20T17:00:00",
    endDate: "2026-02-20T21:00:00",
    timezone: "America/New_York",
    locationName: "Bridge Street and Pine Avenue",
    address: "Bridge Street, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["art", "gallery"],
    tags: ["art walk", "gallery", "local artists", "free"],
    source: "Fallback",
  },
  {
    id: "arts-2",
    title: "Bradenton Blues Festival",
    summary: "Annual blues music festival featuring national and regional artists.",
    description: "Experience the soulful sounds of the Bradenton Blues Festival, featuring top blues musicians from around the country. Food vendors, craft beer, and an electric atmosphere.",
    startDate: "2026-03-15T12:00:00",
    endDate: "2026-03-15T22:00:00",
    timezone: "America/New_York",
    locationName: "Lakewood Ranch",
    address: "8330 Lakewood Ranch Blvd, Bradenton, FL",
    city: "Bradenton",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["music", "festival"],
    tags: ["blues", "music festival", "outdoor", "ticketed"],
    source: "Fallback",
  },
  {
    id: "arts-3",
    title: "Village of the Arts First Friday Gallery Walk",
    summary: "Monthly evening gallery walk in Bradenton's historic arts district.",
    description: "Join artists and art lovers for the First Friday Gallery Walk in the Village of the Arts. Explore working artist studios, galleries, and enjoy live music and refreshments.",
    startDate: "2026-02-06T18:00:00",
    endDate: "2026-02-06T21:00:00",
    timezone: "America/New_York",
    locationName: "Village of the Arts",
    address: "1112 12th St W, Bradenton, FL",
    city: "Bradenton",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["art", "gallery"],
    tags: ["gallery walk", "first friday", "art district", "free"],
    source: "Fallback",
  },
  {
    id: "arts-4",
    title: "Anna Maria Island Historical Society Museum Exhibition",
    summary: "Historical exhibition showcasing island heritage and maritime history.",
    description: "Discover the rich history of Anna Maria Island through this special exhibition at the Historical Society Museum. Features artifacts, photographs, and stories from the island's past.",
    startDate: "2026-02-10T10:00:00",
    endDate: "2026-02-10T16:00:00",
    timezone: "America/New_York",
    locationName: "Anna Maria Island Historical Society",
    address: "402 Pine Ave, Anna Maria, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["art", "history"],
    tags: ["museum", "history", "exhibition", "educational"],
    source: "Fallback",
  },
  // Sports Events
  {
    id: "sports-1",
    title: "Anna Maria Island Fishing Tournament",
    summary: "Annual fishing tournament with prizes for biggest catches in multiple categories.",
    description: "Join local anglers for the annual Anna Maria Island Fishing Tournament. Categories include snook, redfish, trout, and more. Great prizes, family-friendly atmosphere, and celebration of island fishing culture.",
    startDate: "2026-04-12T07:00:00",
    endDate: "2026-04-12T15:00:00",
    timezone: "America/New_York",
    locationName: "Bradenton Beach City Pier",
    address: "Bridge Street Pier, Bradenton Beach, FL",
    city: "Bradenton Beach",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["sport", "tournament"],
    tags: ["fishing", "tournament", "outdoor", "family"],
    source: "Fallback",
  },
  {
    id: "sports-2",
    title: "Bradenton Marathon & 5K",
    summary: "Annual marathon and 5K race through downtown Bradenton and along the waterfront.",
    description: "Challenge yourself with the Bradenton Marathon or join the 5K fun run. Both courses showcase beautiful waterfront views and historic downtown Bradenton. Perfect for runners of all levels.",
    startDate: "2026-03-08T07:00:00",
    endDate: "2026-03-08T12:00:00",
    timezone: "America/New_York",
    locationName: "Downtown Bradenton",
    address: "Old Main Street, Bradenton, FL",
    city: "Bradenton",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["sport", "run", "race"],
    tags: ["marathon", "5k", "running", "fitness"],
    source: "Fallback",
  },
  {
    id: "sports-3",
    title: "Beach Volleyball Tournament",
    summary: "Sandy beach volleyball tournament with teams competing in multiple divisions.",
    description: "Spike, set, and score at the annual Beach Volleyball Tournament on Coquina Beach. Multiple divisions from recreational to competitive, with prizes and a beach party atmosphere.",
    startDate: "2026-05-18T09:00:00",
    endDate: "2026-05-18T17:00:00",
    timezone: "America/New_York",
    locationName: "Coquina Beach",
    address: "Coquina Beach, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["sport", "tournament"],
    tags: ["volleyball", "beach", "tournament", "teams"],
    source: "Fallback",
  },
  {
    id: "sports-4",
    title: "Gulf Coast Pickleball Championship",
    summary: "Regional pickleball tournament attracting players from across Florida.",
    description: "Join the fastest-growing sport in America at the Gulf Coast Pickleball Championship. Multiple skill levels, great prizes, and a celebration of pickleball community.",
    startDate: "2026-04-26T08:00:00",
    endDate: "2026-04-26T18:00:00",
    timezone: "America/New_York",
    locationName: "G.T. Bray Recreation Center",
    address: "5502 33rd Ave Dr W, Bradenton, FL",
    city: "Bradenton",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["sport", "tournament"],
    tags: ["pickleball", "tournament", "indoor", "all ages"],
    source: "Fallback",
  },
  // Parades & Celebrations
  {
    id: "parade-1",
    title: "Anna Maria Island St. Patrick's Day Parade",
    summary: "Annual St. Patrick's Day parade with floats, bands, and community celebration.",
    description: "Join the island's annual St. Patrick's Day Parade featuring colorful floats, local marching bands, community groups, and plenty of green attire. Parade route runs through Holmes Beach with festivities afterwards.",
    startDate: "2026-03-17T10:00:00",
    endDate: "2026-03-17T12:00:00",
    timezone: "America/New_York",
    locationName: "Holmes Beach",
    address: "Marine Drive, Holmes Beach, FL",
    city: "Holmes Beach",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["parade", "celebration"],
    tags: ["st patrick's day", "parade", "free", "family"],
    source: "Fallback",
  },
  {
    id: "parade-2",
    title: "Fourth of July Parade & Fireworks",
    summary: "Independence Day parade followed by fireworks celebration on the beach.",
    description: "Celebrate America's birthday with a traditional Fourth of July parade through Anna Maria Island, followed by spectacular fireworks over the Gulf. Parade features floats, classic cars, and community groups.",
    startDate: "2026-07-04T17:00:00",
    endDate: "2026-07-04T21:30:00",
    timezone: "America/New_York",
    locationName: "Pine Avenue to Coquina Beach",
    address: "Pine Avenue, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["parade", "celebration", "holiday"],
    tags: ["independence day", "parade", "fireworks", "free"],
    source: "Fallback",
  },
  {
    id: "parade-3",
    title: "Anna Maria Island Christmas Parade",
    summary: "Holiday parade with decorated boats, floats, and Santa Claus.",
    description: "Experience island holiday magic at the annual Christmas Parade featuring decorated boat floats, marching bands, community groups, and a special appearance by Santa Claus. Route follows Gulf Drive with viewing areas throughout.",
    startDate: "2026-12-10T18:00:00",
    endDate: "2026-12-10T20:00:00",
    timezone: "America/New_York",
    locationName: "Gulf Drive",
    address: "Gulf Drive, Anna Maria Island, FL",
    city: "Anna Maria",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["parade", "celebration", "holiday"],
    tags: ["christmas", "parade", "boats", "santa", "free"],
    source: "Fallback",
  },
  {
    id: "parade-4",
    title: "Mardi Gras Beach Celebration",
    summary: "Beachside Mardi Gras celebration with music, food, and festive atmosphere.",
    description: "Bring the New Orleans spirit to Anna Maria Island with this beachside Mardi Gras celebration. Features live music, Cajun food vendors, costume contests, and family-friendly festivities.",
    startDate: "2026-02-25T16:00:00",
    endDate: "2026-02-25T22:00:00",
    timezone: "America/New_York",
    locationName: "Manatee Public Beach",
    address: "4000 State Road 64, Bradenton Beach, FL",
    city: "Bradenton Beach",
    state: "FL",
    url: "https://www.bradentongulfislands.com/events/",
    categories: ["celebration", "festival"],
    tags: ["mardi gras", "beach", "music", "food", "family"],
    source: "Fallback",
  },
];
